import Head from "next/head";
import { css } from "@emotion/react";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import IphoneFrame from "@/components/IphoneFrame";
import CameraButtonGroup from "@/components/CameraButtonGroup";
import PhotoSlide from "@/components/PhotoSlide";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const variables: Record<string, string> = {
    "--phone-width": "300px",
    "--phone-height": "600px",
    "--phone-radius": "30px",
    "--phone-border": "2px",
    "--font-size": "12px",
    "--camera-button-diameter": "50px",
  };
  const [tick, setTick] = useState(0);
  useEffect((): (() => void) => {
    const timer = setInterval(() => {
      setTick((tick) => tick + 1);
    }, 3000);

    return (): void => {
      clearTimeout(timer);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={variables}>
        <IphoneFrame>
          <div
            css={css`
              display: flex;
              flex-direction: column;
              justify-content: flex-end;
              width: 100%;
              height: 100%;
            `}
          >
            <PhotoSlide tick={tick} />

            <CameraButtonGroup tick={tick} />
          </div>
        </IphoneFrame>
      </main>
    </>
  );
}
