import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import IphoneFrame from "@/components/IphoneFrame";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const variables: Record<string, string> = {
    "--phone-width": "350px",
    "--phone-height": "700px",
    "--phone-radius": "30px",
    "--phone-border": "2px",
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={variables}>
        <IphoneFrame>
          <div>
            <Image
              src="/photos/photo.png"
              alt="lens"
              width={462}
              height={614}
            />
          </div>
        </IphoneFrame>
      </main>
    </>
  );
}
